// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppYte.Models;

namespace WebAppYte.Migrations
{
    [DbContext(typeof(WebDatLichKhamContext))]
    partial class WebDatLichKhamContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("WebAppYte.Models.BaiViet", b =>
                {
                    b.Property<int>("Mabv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mabv")
                        .UseIdentityColumn();

                    b.Property<string>("Hinhanh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("hinhanh");

                    b.Property<int?>("Maloai")
                        .HasColumnType("int")
                        .HasColumnName("maloai");

                    b.Property<int?>("Mand")
                        .HasColumnType("int")
                        .HasColumnName("mand");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mota");

                    b.Property<DateTime?>("Ngaydang")
                        .HasColumnType("date")
                        .HasColumnName("ngaydang");

                    b.Property<string>("Noidung")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noidung");

                    b.Property<string>("Tieude")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tieude");

                    b.HasKey("Mabv")
                        .HasName("PK__BaiViet__7A2255EC4B636982");

                    b.HasIndex("Maloai");

                    b.HasIndex("Mand");

                    b.ToTable("BaiViet");
                });

            modelBuilder.Entity("WebAppYte.Models.BenhAn", b =>
                {
                    b.Property<int>("Maba")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maba")
                        .UseIdentityColumn();

                    b.Property<double>("Bmi")
                        .HasColumnType("float")
                        .HasColumnName("bmi");

                    b.Property<double>("Cannang")
                        .HasColumnType("float")
                        .HasColumnName("cannang");

                    b.Property<double>("Chieucao")
                        .HasColumnType("float")
                        .HasColumnName("chieucao");

                    b.Property<string>("Chuandoan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("chuandoan");

                    b.Property<DateTime>("Giokham")
                        .HasColumnType("datetime")
                        .HasColumnName("giokham");

                    b.Property<string>("Ketqua")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ketqua");

                    b.Property<int>("Mabn")
                        .HasColumnType("int")
                        .HasColumnName("mabn");

                    b.Property<int>("Mabs")
                        .HasColumnType("int")
                        .HasColumnName("mabs");

                    b.Property<double>("Mach")
                        .HasColumnType("float")
                        .HasColumnName("mach");

                    b.Property<DateTime>("Ngaykham")
                        .HasColumnType("datetime")
                        .HasColumnName("ngaykham");

                    b.Property<double>("NhanapP")
                        .HasColumnType("float")
                        .HasColumnName("nhanapP");

                    b.Property<double>("NhanapT")
                        .HasColumnType("float")
                        .HasColumnName("nhanapT");

                    b.Property<double>("Nhietdo")
                        .HasColumnType("float")
                        .HasColumnName("nhietdo");

                    b.Property<double>("Nhiptho")
                        .HasColumnType("float")
                        .HasColumnName("nhiptho");

                    b.Property<double>("Thilucphai")
                        .HasColumnType("float")
                        .HasColumnName("thilucphai");

                    b.Property<double>("Thiluctrai")
                        .HasColumnType("float")
                        .HasColumnName("thiluctrai");

                    b.Property<string>("Tieude")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tieude");

                    b.Property<int>("Trangthai")
                        .HasColumnType("int")
                        .HasColumnName("trangthai");

                    b.HasKey("Maba")
                        .HasName("PK_dbo.BenhAn");

                    b.HasIndex(new[] { "Mabn" }, "IX_mabn");

                    b.HasIndex(new[] { "Mabs" }, "IX_mabs");

                    b.ToTable("BenhAn");
                });

            modelBuilder.Entity("WebAppYte.Models.BenhNhan", b =>
                {
                    b.Property<int>("Mabn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mabn")
                        .UseIdentityColumn();

                    b.Property<string>("Diachi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("diachi");

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("char(30)")
                        .HasColumnName("email")
                        .IsFixedLength(true);

                    b.Property<string>("Gioitinh")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("gioitinh");

                    b.Property<string>("Mk")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("char(50)")
                        .HasColumnName("mk")
                        .IsFixedLength(true);

                    b.Property<DateTime?>("Ngaysinh")
                        .HasColumnType("date")
                        .HasColumnName("ngaysinh");

                    b.Property<string>("Sdt")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("sdt")
                        .IsFixedLength(true);

                    b.Property<string>("Tenbn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tenbn");

                    b.Property<string>("Tendn")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tendn");

                    b.Property<int?>("Trangthai")
                        .HasColumnType("int")
                        .HasColumnName("trangthai");

                    b.HasKey("Mabn")
                        .HasName("PK__BenhNhan__7A2255F4EC77B831");

                    b.ToTable("BenhNhan");
                });

            modelBuilder.Entity("WebAppYte.Models.CaKham", b =>
                {
                    b.Property<int>("Maca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maca")
                        .UseIdentityColumn();

                    b.Property<string>("Ca")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("char(100)")
                        .HasColumnName("ca")
                        .IsFixedLength(true);

                    b.Property<string>("Hinhthuc")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("hinhthuc");

                    b.Property<int?>("Mand")
                        .HasColumnType("int")
                        .HasColumnName("mand");

                    b.Property<DateTime?>("Ngaykham")
                        .HasColumnType("date")
                        .HasColumnName("ngaykham");

                    b.Property<int?>("Trangthai")
                        .HasColumnType("int")
                        .HasColumnName("trangthai");

                    b.HasKey("Maca")
                        .HasName("PK__CaKham__7A21F87DFBA45D2F");

                    b.HasIndex("Mand");

                    b.ToTable("CaKham");
                });

            modelBuilder.Entity("WebAppYte.Models.ChiNhanh", b =>
                {
                    b.Property<int>("Machinhanh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("machinhanh")
                        .UseIdentityColumn();

                    b.Property<string>("Diachi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("diachi");

                    b.HasKey("Machinhanh")
                        .HasName("PK__ChiNhanh__B98FB2FB9F02B780");

                    b.ToTable("ChiNhanh");
                });

            modelBuilder.Entity("WebAppYte.Models.DangNhap", b =>
                {
                    b.Property<int>("Ma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma")
                        .UseIdentityColumn();

                    b.Property<int?>("Mand")
                        .HasColumnType("int")
                        .HasColumnName("mand");

                    b.Property<string>("Mk")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("char(30)")
                        .HasColumnName("mk")
                        .IsFixedLength(true);

                    b.Property<int?>("Quyen")
                        .HasColumnType("int")
                        .HasColumnName("quyen");

                    b.Property<string>("Tendn")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("char(30)")
                        .HasColumnName("tendn")
                        .IsFixedLength(true);

                    b.HasKey("Ma")
                        .HasName("PK__DangNhap__3213C8B737C80646");

                    b.HasIndex(new[] { "Tendn" }, "UQ__DangNhap__FB739DEF25E948C1")
                        .IsUnique()
                        .HasFilter("[tendn] IS NOT NULL");

                    b.ToTable("DangNhap");
                });

            modelBuilder.Entity("WebAppYte.Models.DanhGia", b =>
                {
                    b.Property<int>("Madanhgia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("madanhgia")
                        .UseIdentityColumn();

                    b.Property<int?>("Mabn")
                        .HasColumnType("int")
                        .HasColumnName("mabn");

                    b.Property<int?>("Mand")
                        .HasColumnType("int")
                        .HasColumnName("mand");

                    b.Property<DateTime?>("Ngay")
                        .HasColumnType("date")
                        .HasColumnName("ngay");

                    b.Property<string>("Noidung")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noidung");

                    b.HasKey("Madanhgia")
                        .HasName("PK__DanhGia__7E089258038F1B8C");

                    b.HasIndex("Mabn");

                    b.HasIndex("Mand");

                    b.ToTable("DanhGia");
                });

            modelBuilder.Entity("WebAppYte.Models.DatLich", b =>
                {
                    b.Property<int>("Madat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("madat")
                        .UseIdentityColumn();

                    b.Property<string>("Hoten")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("hoten");

                    b.Property<int?>("Mabn")
                        .HasColumnType("int")
                        .HasColumnName("mabn");

                    b.Property<int?>("Maca")
                        .HasColumnType("int")
                        .HasColumnName("maca");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mota");

                    b.Property<DateTime?>("Ngaydat")
                        .HasColumnType("date")
                        .HasColumnName("ngaydat");

                    b.Property<DateTime?>("Ngaysinh")
                        .HasColumnType("date")
                        .HasColumnName("ngaysinh");

                    b.Property<string>("Sdt")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("sdt")
                        .IsFixedLength(true);

                    b.Property<int?>("Trangthai")
                        .HasColumnType("int")
                        .HasColumnName("trangthai");

                    b.HasKey("Madat")
                        .HasName("PK__DatLich__0BE68C779C8183A2");

                    b.HasIndex("Maca");

                    b.ToTable("DatLich");
                });

            modelBuilder.Entity("WebAppYte.Models.DiaChiKham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address");

                    b.Property<int>("BsId")
                        .HasColumnType("int")
                        .HasColumnName("bs_id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("city");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Phone")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.HasIndex("BsId");

                    b.ToTable("DiaChiKham");
                });

            modelBuilder.Entity("WebAppYte.Models.HoiDap", b =>
                {
                    b.Property<int>("Ma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma")
                        .UseIdentityColumn();

                    b.Property<string>("Dap")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dap");

                    b.Property<string>("Hoi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("hoi");

                    b.Property<int?>("Mabn")
                        .HasColumnType("int")
                        .HasColumnName("mabn");

                    b.Property<int?>("Mand")
                        .HasColumnType("int")
                        .HasColumnName("mand");

                    b.Property<DateTime?>("Ngayhoi")
                        .HasColumnType("datetime")
                        .HasColumnName("ngayhoi");

                    b.Property<DateTime?>("Ngaytl")
                        .HasColumnType("datetime")
                        .HasColumnName("ngaytl");

                    b.Property<int?>("Trangthai")
                        .HasColumnType("int")
                        .HasColumnName("trangthai");

                    b.HasKey("Ma")
                        .HasName("PK__HoiDap__3213C8B7CA4B4968");

                    b.HasIndex("Mabn");

                    b.HasIndex("Mand");

                    b.ToTable("HoiDap");
                });

            modelBuilder.Entity("WebAppYte.Models.Khoa", b =>
                {
                    b.Property<int>("Makhoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("makhoa")
                        .UseIdentityColumn();

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mota");

                    b.Property<string>("Tenkhoa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tenkhoa");

                    b.HasKey("Makhoa")
                        .HasName("PK__Khoa__30B01682250477C0");

                    b.ToTable("Khoa");
                });

            modelBuilder.Entity("WebAppYte.Models.Loai", b =>
                {
                    b.Property<int>("Maloai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maloai")
                        .UseIdentityColumn();

                    b.Property<string>("Tenloai")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tenloai");

                    b.HasKey("Maloai")
                        .HasName("PK__Loai__734B3AEA67D4DA62");

                    b.ToTable("Loai");
                });

            modelBuilder.Entity("WebAppYte.Models.NguoiDung", b =>
                {
                    b.Property<int>("Mand")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mand")
                        .UseIdentityColumn();

                    b.Property<string>("Anh")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("anh");

                    b.Property<string>("Chucvu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("chucvu");

                    b.Property<string>("Diachi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("diachi");

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("char(30)")
                        .HasColumnName("email")
                        .IsFixedLength(true);

                    b.Property<string>("Gioithieu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gioithieu");

                    b.Property<string>("Gioitinh")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("gioitinh");

                    b.Property<string>("Hocham")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("hocham");

                    b.Property<string>("Hocvi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("hocvi");

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("hoten");

                    b.Property<int?>("Machinhanh")
                        .HasColumnType("int")
                        .HasColumnName("machinhanh");

                    b.Property<int?>("Makhoa")
                        .HasColumnType("int")
                        .HasColumnName("makhoa");

                    b.Property<string>("Mk")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("char(50)")
                        .HasColumnName("mk")
                        .IsFixedLength(true);

                    b.Property<DateTime?>("Ngaysinh")
                        .HasColumnType("date")
                        .HasColumnName("ngaysinh");

                    b.Property<int?>("Quyen")
                        .HasColumnType("int")
                        .HasColumnName("quyen");

                    b.Property<string>("Sdt")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("sdt")
                        .IsFixedLength(true);

                    b.Property<string>("Tendn")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tendn");

                    b.Property<int?>("Trangthai")
                        .HasColumnType("int")
                        .HasColumnName("trangthai");

                    b.HasKey("Mand")
                        .HasName("PK__NguoiDun__7A21B393C7BAA166");

                    b.HasIndex("Machinhanh");

                    b.HasIndex("Makhoa");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("WebAppYte.Models.BaiViet", b =>
                {
                    b.HasOne("WebAppYte.Models.Loai", "MaloaiNavigation")
                        .WithMany("BaiViets")
                        .HasForeignKey("Maloai")
                        .HasConstraintName("FK__BaiViet__maloai__48CFD27E");

                    b.HasOne("WebAppYte.Models.NguoiDung", "MandNavigation")
                        .WithMany("BaiViets")
                        .HasForeignKey("Mand")
                        .HasConstraintName("FK__BaiViet__mand__49C3F6B7");

                    b.Navigation("MaloaiNavigation");

                    b.Navigation("MandNavigation");
                });

            modelBuilder.Entity("WebAppYte.Models.BenhAn", b =>
                {
                    b.HasOne("WebAppYte.Models.BenhNhan", "MabnNavigation")
                        .WithMany("BenhAns")
                        .HasForeignKey("Mabn")
                        .HasConstraintName("FK_dbo.BenhAn_dbo.BenhNhan_mabn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAppYte.Models.NguoiDung", "MabsNavigation")
                        .WithMany("BenhAns")
                        .HasForeignKey("Mabs")
                        .HasConstraintName("FK_dbo.BenhAn_dbo.NguoiDung_mabs")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MabnNavigation");

                    b.Navigation("MabsNavigation");
                });

            modelBuilder.Entity("WebAppYte.Models.CaKham", b =>
                {
                    b.HasOne("WebAppYte.Models.NguoiDung", "MandNavigation")
                        .WithMany("CaKhams")
                        .HasForeignKey("Mand")
                        .HasConstraintName("FK__CaKham__mand__4CA06362");

                    b.Navigation("MandNavigation");
                });

            modelBuilder.Entity("WebAppYte.Models.DanhGia", b =>
                {
                    b.HasOne("WebAppYte.Models.BenhNhan", "MabnNavigation")
                        .WithMany("DanhGia")
                        .HasForeignKey("Mabn")
                        .HasConstraintName("FK__DanhGia__mabn__534D60F1");

                    b.HasOne("WebAppYte.Models.NguoiDung", "MandNavigation")
                        .WithMany("DanhGia")
                        .HasForeignKey("Mand")
                        .HasConstraintName("FK__DanhGia__mand__52593CB8");

                    b.Navigation("MabnNavigation");

                    b.Navigation("MandNavigation");
                });

            modelBuilder.Entity("WebAppYte.Models.DatLich", b =>
                {
                    b.HasOne("WebAppYte.Models.CaKham", "MacaNavigation")
                        .WithMany("DatLiches")
                        .HasForeignKey("Maca")
                        .HasConstraintName("FK__DatLich__maca__4F7CD00D");

                    b.Navigation("MacaNavigation");
                });

            modelBuilder.Entity("WebAppYte.Models.DiaChiKham", b =>
                {
                    b.HasOne("WebAppYte.Models.NguoiDung", "Bs")
                        .WithMany("DiaChiKhams")
                        .HasForeignKey("BsId")
                        .HasConstraintName("FK__DiaChiKha__bs_id__6FE99F9F")
                        .IsRequired();

                    b.Navigation("Bs");
                });

            modelBuilder.Entity("WebAppYte.Models.HoiDap", b =>
                {
                    b.HasOne("WebAppYte.Models.BenhNhan", "MabnNavigation")
                        .WithMany("HoiDaps")
                        .HasForeignKey("Mabn")
                        .HasConstraintName("FK__HoiDap__mabn__571DF1D5");

                    b.HasOne("WebAppYte.Models.NguoiDung", "MandNavigation")
                        .WithMany("HoiDaps")
                        .HasForeignKey("Mand")
                        .HasConstraintName("FK__HoiDap__mand__5629CD9C");

                    b.Navigation("MabnNavigation");

                    b.Navigation("MandNavigation");
                });

            modelBuilder.Entity("WebAppYte.Models.NguoiDung", b =>
                {
                    b.HasOne("WebAppYte.Models.ChiNhanh", "MachinhanhNavigation")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("Machinhanh")
                        .HasConstraintName("FK__NguoiDung__machi__403A8C7D");

                    b.HasOne("WebAppYte.Models.Khoa", "MakhoaNavigation")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("Makhoa")
                        .HasConstraintName("FK__NguoiDung__makho__3F466844");

                    b.Navigation("MachinhanhNavigation");

                    b.Navigation("MakhoaNavigation");
                });

            modelBuilder.Entity("WebAppYte.Models.BenhNhan", b =>
                {
                    b.Navigation("BenhAns");

                    b.Navigation("DanhGia");

                    b.Navigation("HoiDaps");
                });

            modelBuilder.Entity("WebAppYte.Models.CaKham", b =>
                {
                    b.Navigation("DatLiches");
                });

            modelBuilder.Entity("WebAppYte.Models.ChiNhanh", b =>
                {
                    b.Navigation("NguoiDungs");
                });

            modelBuilder.Entity("WebAppYte.Models.Khoa", b =>
                {
                    b.Navigation("NguoiDungs");
                });

            modelBuilder.Entity("WebAppYte.Models.Loai", b =>
                {
                    b.Navigation("BaiViets");
                });

            modelBuilder.Entity("WebAppYte.Models.NguoiDung", b =>
                {
                    b.Navigation("BaiViets");

                    b.Navigation("BenhAns");

                    b.Navigation("CaKhams");

                    b.Navigation("DanhGia");

                    b.Navigation("DiaChiKhams");

                    b.Navigation("HoiDaps");
                });
#pragma warning restore 612, 618
        }
    }
}
